// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     record.avro
 */
package dtsavro

import (
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

func writeArrayUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject(r []*UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectWrapper struct {
	Target *[]*UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject
}

func (_ *ArrayUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectWrapper) SetBoolean(v bool) {
	panic("Unsupported operation")
}
func (_ *ArrayUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectWrapper) SetInt(v int32) {
	panic("Unsupported operation")
}
func (_ *ArrayUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectWrapper) SetLong(v int64) {
	panic("Unsupported operation")
}
func (_ *ArrayUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectWrapper) SetFloat(v float32) {
	panic("Unsupported operation")
}
func (_ *ArrayUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectWrapper) SetDouble(v float64) {
	panic("Unsupported operation")
}
func (_ *ArrayUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectWrapper) SetBytes(v []byte) {
	panic("Unsupported operation")
}
func (_ *ArrayUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectWrapper) SetString(v string) {
	panic("Unsupported operation")
}
func (_ *ArrayUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectWrapper) SetUnionElem(v int64) {
	panic("Unsupported operation")
}
func (_ *ArrayUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectWrapper) Get(i int) types.Field {
	panic("Unsupported operation")
}
func (_ *ArrayUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectWrapper) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *ArrayUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectWrapper) Finalize() {
}
func (_ *ArrayUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectWrapper) SetDefault(i int) {
	panic("Unsupported operation")
}
func (r *ArrayUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectWrapper) NullField(i int) {
	(*r.Target)[len(*r.Target)-1] = nil
}

func (r *ArrayUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectWrapper) AppendArray() types.Field {
	var v *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject
	v = NewUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject()

	*r.Target = append(*r.Target, v)

	return (*r.Target)[len(*r.Target)-1]
}
