// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     record.avro
 */
package dtsavro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnum int

const (
	UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumCharacter UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnum = 1

	UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumFloat UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnum = 2

	UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumTimestamp UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnum = 3

	UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumDateTime UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnum = 4

	UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumTimestampWithTimeZone UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnum = 5

	UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumBinaryGeometry UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnum = 6

	UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumTextGeometry UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnum = 7

	UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumBinaryObject UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnum = 8

	UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumTextObject UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnum = 9

	UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumEmptyObject UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnum = 10
)

type UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject struct {
	Null                  *types.NullVal
	Character             *Character
	Float                 *Float
	Timestamp             *Timestamp
	DateTime              *DateTime
	TimestampWithTimeZone *TimestampWithTimeZone
	BinaryGeometry        *BinaryGeometry
	TextGeometry          *TextGeometry
	BinaryObject          *BinaryObject
	TextObject            *TextObject
	EmptyObject           EmptyObject
	UnionType             UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnum
}

func writeUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject(r *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumCharacter:
		return writeCharacter(r.Character, w)
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumFloat:
		return writeFloat(r.Float, w)
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumTimestamp:
		return writeTimestamp(r.Timestamp, w)
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumDateTime:
		return writeDateTime(r.DateTime, w)
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumTimestampWithTimeZone:
		return writeTimestampWithTimeZone(r.TimestampWithTimeZone, w)
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumBinaryGeometry:
		return writeBinaryGeometry(r.BinaryGeometry, w)
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumTextGeometry:
		return writeTextGeometry(r.TextGeometry, w)
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumBinaryObject:
		return writeBinaryObject(r.BinaryObject, w)
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumTextObject:
		return writeTextObject(r.TextObject, w)
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumEmptyObject:
		return writeEmptyObject(r.EmptyObject, w)
	}
	return fmt.Errorf("invalid value for *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject")
}

func NewUnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject() *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject {
	return &UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject{}
}

func (_ *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject) SetBoolean(v bool) {
	panic("Unsupported operation")
}
func (_ *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject) SetInt(v int32) {
	panic("Unsupported operation")
}
func (_ *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject) SetFloat(v float32) {
	panic("Unsupported operation")
}
func (_ *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject) SetDouble(v float64) {
	panic("Unsupported operation")
}
func (_ *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject) SetBytes(v []byte) {
	panic("Unsupported operation")
}
func (_ *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject) SetString(v string) {
	panic("Unsupported operation")
}
func (r *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject) SetLong(v int64) {
	r.UnionType = (UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnum)(v)
}
func (r *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject) Get(i int) types.Field {
	switch i {
	case 0:
		return r.Null
	case 1:
		r.Character = NewCharacter()
		return r.Character
	case 2:
		r.Float = NewFloat()
		return r.Float
	case 3:
		r.Timestamp = NewTimestamp()
		return r.Timestamp
	case 4:
		r.DateTime = NewDateTime()
		return r.DateTime
	case 5:
		r.TimestampWithTimeZone = NewTimestampWithTimeZone()
		return r.TimestampWithTimeZone
	case 6:
		r.BinaryGeometry = NewBinaryGeometry()
		return r.BinaryGeometry
	case 7:
		r.TextGeometry = NewTextGeometry()
		return r.TextGeometry
	case 8:
		r.BinaryObject = NewBinaryObject()
		return r.BinaryObject
	case 9:
		r.TextObject = NewTextObject()
		return r.TextObject
	case 10:
		return &EmptyObjectWrapper{Target: (&r.EmptyObject)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject) NullField(i int) {
	panic("Unsupported operation")
}
func (_ *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject) SetDefault(i int) {
	panic("Unsupported operation")
}
func (_ *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject) AppendArray() types.Field {
	panic("Unsupported operation")
}
func (_ *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject) Finalize() {
}

func (r *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumCharacter:
		return json.Marshal(map[string]interface{}{"Character": r.Character})
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumFloat:
		return json.Marshal(map[string]interface{}{"Float": r.Float})
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumTimestamp:
		return json.Marshal(map[string]interface{}{"Timestamp": r.Timestamp})
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumDateTime:
		return json.Marshal(map[string]interface{}{"DateTime": r.DateTime})
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumTimestampWithTimeZone:
		return json.Marshal(map[string]interface{}{"TimestampWithTimeZone": r.TimestampWithTimeZone})
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumBinaryGeometry:
		return json.Marshal(map[string]interface{}{"BinaryGeometry": r.BinaryGeometry})
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumTextGeometry:
		return json.Marshal(map[string]interface{}{"TextGeometry": r.TextGeometry})
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumBinaryObject:
		return json.Marshal(map[string]interface{}{"BinaryObject": r.BinaryObject})
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumTextObject:
		return json.Marshal(map[string]interface{}{"TextObject": r.TextObject})
	case UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectTypeEnumEmptyObject:
		return json.Marshal(map[string]interface{}{"EmptyObject": r.EmptyObject})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject")
}

func (r *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["Character"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.Character)
	}
	if value, ok := fields["Float"]; ok {
		r.UnionType = 2
		return json.Unmarshal([]byte(value), &r.Float)
	}
	if value, ok := fields["Timestamp"]; ok {
		r.UnionType = 3
		return json.Unmarshal([]byte(value), &r.Timestamp)
	}
	if value, ok := fields["DateTime"]; ok {
		r.UnionType = 4
		return json.Unmarshal([]byte(value), &r.DateTime)
	}
	if value, ok := fields["TimestampWithTimeZone"]; ok {
		r.UnionType = 5
		return json.Unmarshal([]byte(value), &r.TimestampWithTimeZone)
	}
	if value, ok := fields["BinaryGeometry"]; ok {
		r.UnionType = 6
		return json.Unmarshal([]byte(value), &r.BinaryGeometry)
	}
	if value, ok := fields["TextGeometry"]; ok {
		r.UnionType = 7
		return json.Unmarshal([]byte(value), &r.TextGeometry)
	}
	if value, ok := fields["BinaryObject"]; ok {
		r.UnionType = 8
		return json.Unmarshal([]byte(value), &r.BinaryObject)
	}
	if value, ok := fields["TextObject"]; ok {
		r.UnionType = 9
		return json.Unmarshal([]byte(value), &r.TextObject)
	}
	if value, ok := fields["EmptyObject"]; ok {
		r.UnionType = 10
		return json.Unmarshal([]byte(value), &r.EmptyObject)
	}
	return fmt.Errorf("invalid value for *UnionNullCharacterFloatTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObject")
}
